### PR TITLE
URL Path and query parameter filtering

### LINKED ISSUE #223: Add configuration to filter URI params in requests context
Currently we aren't filtering parameters in the URI context.

The way to deal with this issue currently is to just override this with an empty string
`$this->agent->changeRequestUri('')`

But this has to be done client side, and isn't as nice as a configuration setting, and it loses visibility into potential parameters that can help track down performance issues

In the Ruby and Python agent, there's a configuration of [uri_reporting](https://scoutapm.com/docs/ruby/configuration#uri_reporting) which takes two options, a default value of "filtered_params" as well a "path" value. If "filtered_params" is set, we will filter the params, if "path" is set, we only return the path and not the full URI:
https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/core/web_requests.py#L43-L71

One thing we don't have in these is the ability to add a JSON array of additional values to filter, which would be nice to have (maybe with a configuration name of `uri_filtered_params` that can be merged into the default filtered list):
https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/core/web_requests.py#L15-L40

Something similar to Ruby's `errors_filtered_params` but for URI parameters and not exceptions:
https://scoutapm.com/docs/ruby/configuration#errors_filtered_params

### PR DESCRIPTION
**Pull request by asgrim**
Fixes #223 

Adds new `uri_reporting` and `uri_filtered_params` configurations to control filtering URL paths and query parameters.

### CODE REVIEW

**Comment by mkopinsky** [comment]
Thanks for this!

Is there any documentation on how to use this? I gather that it's something like this?

```
SCOUT_URI_REPORTING=filtered_params
SCOUT_URI_FILTERED_PARAMS='["foo","bar","baz"]'
```

**Comment by asgrim** [comment]
@mkopinsky it needs documenting properly, `SCOUT_URI_REPORTING` can have one of three values (given a URL like `/path/to/the/thing?a=b`:

 * `path`, will only have `/path/to/the/thing` - this will be the new default in `6.4.0` onwards
 * `filtered_params` will filter the parameters, there is a default list (see `\Scoutapm\Config\Source\DefaultSource::getDefaultConfig` for the default values) or you can replace the whole list with `SCOUT_URI_FILTERED_PARAMS` - note the lists are not merged, so if you want the default ones as well you'd have to add them
 * `full_path` - returns the full path (current behaviour in `6.3.0`)

Note: this is merged, but not yet released (will be in `6.4.0` release)

**Comment by mkopinsky** [comment]
Is `SCOUT_URI_FILTERED_PARAMS` a JSON list like I had in my example? I'm assuming so given that the [config docs](https://scoutapm.com/docs/php/configuration) say JSON list for some other things (e.g. `disabled_instruments`).

It appears that filtered params will under the scenes convert http://example.com?filteredParam=x&other=y to http://example.com?other=y. Is there any interest in instead redacting it to e.g. `http://example.com?filteredParam=<redacted>&other=y` rather than wiping its existence? I figure consistency with the other language SDKs is probably the overriding factor, but for my use case, I'd like to know that a certain parameter existed even if I don't want Scout to see the value of the parameter. (As a concrete use case, knowing that `/api/v2/participants?cell_phone=<redacted>` is slow tells me what index I need to add to the table, but I can't send the PII cell phone because of HIPAA.)

**Comment by asgrim** [comment]
@mkopinsky 

> Is `SCOUT_URI_FILTERED_PARAMS` a JSON list like I had in my example?

Yes that is correct, and also thank you for checking as you reminded me to add the conversion for it :) #232 fixes this :)

> Is there any interest in instead redacting it to e.g. `http://example.com?filteredParam=<redacted>&other=y` rather than wiping its existence?

I'll ask @dlanderson to take a look at this :)

**Pull request merged**
